name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          matrix:
  config:
    - name: Windows
      os: windows-latest
      target: Win64
    - name: Android64
      os: ubuntu-latest
      target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Android NDK
        if: runner.os == 'Linux'
        run: |
          echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;28.1.13356709"
        shell: bash

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
          android-ndk-version: "28.1.13356709"
